name: Run Automated Testcases
run-name: API Automation
on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
     
jobs:

  Run-API-Automation:
    timeout-minutes : 30
    runs-on: ubuntu-latest
    
    steps:
      - name : Checkout repo
        uses : actions/checkout@v3
        
      - name : Run API test
        run : |
          mvn clean test -DisRemote=yes
        
  Clean-up:
    runs-on: ubuntu-latest
    if : ${{failure()}}
    needs : [Run-API-Automation]
    steps:
      - name : Log failure
        run : |
          echo 'API automation failed, please check the logs'
          echo ${{secrets.MAIL_USERNAME}}
          echo ${{secrets.MAIL_PASSWORD}}
          
  Trigger-UI-Automation: 
    runs-on: ubuntu-latest
    if : ${{success()}}
    needs : [Run-API-Automation]
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: pavithra2006/Selenium-Testng-ExtentReport-Docker
          event-type: my-event
        
  Trigger-email:
    runs-on: ubuntu-latest
    needs : [ Run-API-Automation] 
    steps: 
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions API AUTOMATION job result
          to: pavi2098@gmail.com, pavithrasathya2098@gmail.com
          from: ABC ord  # <abc@org.com>
          body: Build job of ${{github.repository}} completed successfully! + some attachements
          attachments: ./extent-test-output/index.html, RestAssured-Testng-Docker-Githubactions/.github/workflows/mail.yml
