name: daily-cron-workflow
run-name: API Automation
on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
     
jobs:

  Run-API-Automation:
    timeout-minutes : 30
    
    runs-on: ubuntu-latest
    
    steps:
      - name : Set-up jdk 11
        uses : actions/setup-java@v1
        with:
          java-version : 11
      
      - name : Checkout repo
        uses : actions/checkout@v3
        
      - name : Run API test
        run : |
          mvn clean test -DisRemote=yes
        
  Clean-up:
    runs-on: ubuntu-latest
    if : ${{failure()}}
    needs : [Run-API-Automation]
    steps:
      - name : Log failure
        run : echo 'API automation failed, please check the logs'
        
  Trigger-email:
    runs-on: ubuntu-latest
    needs : [ Run-API-Automation] 
    steps: 
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          # Optional (recommended) mail server username:
          username: ${{secrets.MAIL_USERNAME}}
          # Optional (recommended) mail server password:
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions API AUTOMATION job result
          to: pavi2098@gmail.com, pavithrasathya2098@gmail.com
          from: Luke Skywalker # <user@example.com>
          body: Build job of ${{github.repository}} completed successfully!
    
     
   
