name: daily-cron-workflow
run-name: API Automation
on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
     
jobs:

  Run-API-Automation:
    timeout-minutes : 30
    
    runs-on: ubuntu-latest
    
    steps:
      - name : Set-up jdk 11
        uses : actions/setup-java@v1
        with:
          java-version : 11
      
      - name : Checkout repo
        uses : actions/checkout@v3
        
      - name : Run API test
        run : |
          mvn clean test -DisRemote=yes
        
  Clean-up:
    runs-on: ubuntu-latest
    if : ${{failure()}}
    needs : [Run-API-Automation]
    steps:
      - name : Log failure
        run : echo 'API automation failed, please check the logs'
     
   
