name: Run Automated Testcases
run-name: API Automation
on:
  push:
    branches:
      - main
      - 'release/**'
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *
     
jobs:
  Run-API-Automation:
    timeout-minutes : 30
    runs-on: ubuntu-latest
    
    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
        contents: write
    
    steps:
      - name : Checkout repo
        uses : actions/checkout@v3
        
      - name : Run API test
        run : |
          mvn clean test -DisRemote=yes
        
      - name: Commit to master
        uses: stefanzweifel/git-auto-commit-action@v4
          with:
            commit_message: Commit index.html

        
  Clean-up:
    runs-on: ubuntu-latest
    #if : ${{failure()}}
    needs : [Run-API-Automation]
    steps:
      - name : Log failure
        run : |
          echo 'API automation failed, please check the logs'
          echo ${GITHUB_WORKSPACE}
          
  Trigger-UI-Automation: 
    runs-on: ubuntu-latest
    if : ${{success()}}
    needs : [Run-API-Automation]
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: pavithra2006/Selenium-Testng-ExtentReport-Docker
          event-type: my-event
        
  Trigger-email:
    runs-on: ubuntu-latest
    needs : [ Run-API-Automation] 
    steps: 
      - name : Checkout repo
        uses : actions/checkout@v3
        
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          # Server port, default 25:
          server_port: 465
          # Optional whether this connection use TLS (default is true if server_port is 465)
          secure: true
          username: ${{secrets.MAIL_USERNAME}}
          password: ${{secrets.MAIL_PASSWORD}}
          # Required mail subject:
          subject: Github Actions API AUTOMATION job result
          to: pavi2098@gmail.com, pavithrasathya2098@gmail.com
          from: ABC ord  # <abc@org.com>
          body: this is body
          attachments: ./index.html
